---
# Playbook to undeploy Moonshot and its components
- name: "postgres & moonshot"
  hosts: localhost
  gather_facts: false
  vars_files:
    - /inventory/gcp.yml  
  roles:
    - role: postgres-undeploy
      tags: ["postgres-undeploy"]
    - role: moonshot-undeploy
      tags: ["moonshot-undeploy"]  
