- name: Delete moonshot deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: moonshot-deployment
    namespace: default

- name: Delete moonshot service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: moonshot-service
    namespace: default


