apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot-deployment
  namespace: default # Garantir que o namespace seja o correto
  labels:
    app: moonshot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot
  template:
    metadata:
      labels:
        app: moonshot
    spec:
      containers:
      - name: moonshot
        image: "henrique020/moonshot"
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_DATABASE
          value: "dbname"
        - name: DB_USERNAME
          value: "dbuser"
        - name: DB_PASSWORD
          value: "password"
        - name: SEED
          value: "{{ seed_database | ternary('true', 'false') }}"
  
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "350m"
            memory: "512Mi"  