apiVersion: v1
kind: Service
metadata:
  name: moonshot-service
  labels:
    app: moonshot
  namespace: default
spec:
  type: LoadBalancer # Permite expor um IP público
  selector:
    app: moonshot
  ports:
    - targetPort: 8000 # Porta que o container escuta
      port: 8000 # Porta acessível dentro do cluster
