- name: Create dashboard config file
  template:
    src: dashboards/MyDashASCN.json
    dest: dashboards/dashboard_config.json

- name: Create Dashboard
  shell: "gcloud monitoring dashboards create --config-from-file=dashboards/dashboard_config.json"
# ver se o nome acima muda - 