apiVersion: v1
kind: Service
metadata:
  name: "postgres-service"
  labels:
    app: postgres
    tier: database
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - targetPort: 8000 
      port: 8000        
